name: Publish @Vimoxx/ux-web

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Vimoxx/jellyfin-ux' }}

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instala Node.js y configura cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          cache: 'npm'
          cache-dependency-path: ./branding/web/package-lock.json

      # 3. Instala dependencias usando el lockfile
      - name: Install dependencies
        working-directory: ./branding/web
        run: npm ci --no-audit

      # 4. Publica en GitHub Packages
      - name: Publish to GitHub Packages
        working-directory: ./branding/web
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
